name: Build and test


on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  local_test_jobs:
     name: Running Local Tests
     runs-on: ubuntu-latest
     continue-on-error: true
     steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: cache
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Debug Tests
        run: ./gradlew testDebugUnitTest --continue
      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'

     
        
        
     
